# Generated by Django 3.2.13 on 2022-05-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwn_event', '0002_auto_20220511_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='speaker',
            new_name='speakers',
        ),
        migrations.AlterField(
            model_name='speaker',
            name='first_Name',
            field=models.CharField(max_length=250, unique=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='last_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='last name'),
        ),
    ]
