# Generated by Django 3.2.13 on 2022-05-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwn_event', '0003_auto_20220512_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='town',
        ),
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='city'),
        ),
    ]
