# Generated by Django 3.2.23 on 2024-06-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwn_event', '0008_rename_first_name_speaker_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='pwn_event.Tag'),
        ),
    ]
