# Generated by Django 3.2.23 on 2024-06-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwn_event', '0009_alter_event_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='pwn_event.Tag'),
        ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
