# Generated by Django 3.2.23 on 2024-06-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pwn_event', '0010_auto_20240627_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'get_latest_by': '-start_date', 'ordering': ['name'], 'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='pwn_event.place', verbose_name='place'),
        ),
    ]
