# Generated by Django 3.2.23 on 2024-06-27 13:45

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pwn_event', '0011_auto_20240627_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=['last_name', 'first_name'], verbose_name='slug'),
        ),
    ]
