# Generated by Django 3.2.23 on 2024-06-27 13:45

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pwn_event', '0012_alter_speaker_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='first_name',
            field=models.CharField(max_length=250, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='last_name',
            field=models.CharField(max_length=250, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=['last_name', 'first_name'], unique=True, verbose_name='slug'),
        ),
    ]
