# Generated by Django 4.2.13 on 2024-09-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pwn_event", "0013_auto_20240627_1545"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "get_latest_by": "-date",
                "ordering": ("-date",),
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="n8n",
            field=models.BooleanField(
                default=True,
                help_text="La conférence est-elle visible par n8n ?",
                verbose_name="n8n",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_publish",
            field=models.BooleanField(default=False, verbose_name="is publish"),
        ),
        migrations.AlterField(
            model_name="event",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="pwn_event.season",
                verbose_name="season",
            ),
        ),
    ]
