# Generated by Django 4.2.16 on 2024-09-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "pwn_event",
            "0014_alter_event_options_event_n8n_alter_event_is_publish_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="speakers",
            field=models.ManyToManyField(blank=True, to="pwn_event.speaker"),
        ),
        migrations.AlterField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(blank=True, to="pwn_event.tag"),
        ),
    ]
