# Generated by Django 4.2.16 on 2024-09-10 11:05

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("pwn_event", "0015_alter_event_speakers_alter_event_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="excerpt",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="excerpt"
            ),
        ),
    ]
